Use curly braces only where required #9.

diff --git a/bin/vee b/bin/vee
--- a/bin/vee
+++ b/bin/vee
@@ -5,22 +5,22 @@
 
 VERSION=1.00
 
-if [ ! "${EDITOR}" ]; then
+if [ ! "$EDITOR" ]; then
   EDITOR=vi
 fi
 MARGIN=64
 FORMAT=html
 INDEX=vee.html
 DIR=.vee
-DRAFT="${DIR}/.vee.tmp.$$"
+DRAFT="$DIR/.vee.tmp.$$"
 DATE=$(date)
 YEAR=$(date "+%Y")
 TIME=$(date "+%Y-%m-%dT%H:%M:%S")
 SEC=$(date "+%s")
 TITLE=
-DEFAULT_TITLE="Entry #${SEC}";
+DEFAULT_TITLE="Entry #$SEC";
 HEADERTXT=  # text or $(cat some.header.txt)
-FOOTERTXT="Powered by <a href=\"http://www.0x743.com/vee\">vee</a><br/>Copyright &copy; 2006-${YEAR}"  
+FOOTERTXT="Powered by <a href=\"http://www.0x743.com/vee\">vee</a><br/>Copyright &copy; 2006-$YEAR"  
 TOP_TPL=./vee-top.tpl
 BOT_TPL=./vee-bottom.tpl
 PREFORMAT_HOOK=./vee-pre # the hook is assumed to be executable, else it is ignored
@@ -116,10 +116,10 @@ CUSTOM_SETUP=default_setup
              echo using $FORMAT_FUNC
              ;;
              # if not a supplied format, see if it is in the custom format file, if it exists
-    *)       if [ -e "${FORMAT_CUSTOM_DEFS}" ]; then
+    *)       if [ -e "$FORMAT_CUSTOM_DEFS" ]; then
                # call dispatch function that is defined in
                # the custom format file, pass on format nickname
-               ${FORMAT_CUSTOM_DISPATCHER} "${1}"
+               $FORMAT_CUSTOM_DISPATCHER "$1"
              else
                echo "bad format type" 
                die_cleanly
@@ -131,7 +131,7 @@ CUSTOM_SETUP=default_setup
 { echo "                                                                              " 
   echo " vee - the Zero-conf, commandline blog tool thingy                            "
   echo "                                                                              "
-  echo "Version: ${VERSION}                                                           "
+  echo "Version: $VERSION                                                           "
   echo "                                                                              "
   echo "Usage:                                                                        "
   echo "  See below.                                                                  " 
@@ -215,39 +215,39 @@ CUSTOM_SETUP=default_setup
 
 # formats post link on index page
  default_update_index() 
-{ echo "<!-- ;${SEC}; -->${PUBLISHED}:<a href=\"${DIR}/${SEC}.${TIME}.${FORMAT}\"> ${TITLE}</a>" >> ${INDEX}
-  if [ -n "${SUMMARY}" ]; then
+{ echo "<!-- ;$SEC; -->$PUBLISHED:<a href=\"$DIR/$SEC.$TIME.$FORMAT\"> $TITLE</a>" >> $INDEX
+  if [ -n "$SUMMARY" ]; then
 	SEC=$(expr "$SEC" - 1)
-    echo "<!-- ;${SEC}; -->${SUMMARY}" >> "${INDEX}"
+    echo "<!-- ;$SEC; -->$SUMMARY" >> "$INDEX"
   fi
 }
 
  output_top()
-{ echo "${HEADERTXT}" > "${FINAL}"
-  if [ -e "${TOP_TPL}" ]; then
-     cat "${TOP_TPL}" >> "${FINAL}"
-     echo "<pre>"   >> "${FINAL}"
+{ echo "$HEADERTXT" > "$FINAL"
+  if [ -e "$TOP_TPL" ]; then
+     cat "$TOP_TPL" >> "$FINAL"
+     echo "<pre>"   >> "$FINAL"
    else
-     echo "<!-- <?xml version=\"1.0\" encoding=\"UTF-8\" ?> --><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\">"  >> "${FINAL}"
-     echo "<meta http-equiv=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">" >> "${FINAL}"
-     echo "<head><title>${TITLE} - ${DATE}</title></head>"  >> "${FINAL}"
-     echo "<body>"  >> "${FINAL}"
-     echo "<pre>"   >> "${FINAL}"
-     echo "<a href=\"../${INDEX}\">[index]</a><a href=\"./${RAWNAME}\">[raw]</a><a href=\"../\">[main]</a>" >> "${FINAL}"
+     echo "<!-- <?xml version=\"1.0\" encoding=\"UTF-8\" ?> --><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\">"  >> "$FINAL"
+     echo "<meta http-equiv=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">" >> "$FINAL"
+     echo "<head><title>$TITLE - $DATE</title></head>"  >> "$FINAL"
+     echo "<body>"  >> "$FINAL"
+     echo "<pre>"   >> "$FINAL"
+     echo "<a href=\"../$INDEX\">[index]</a><a href=\"./$RAWNAME\">[raw]</a><a href=\"../\">[main]</a>" >> "$FINAL"
    fi
-   echo           >> "${FINAL}"
+   echo           >> "$FINAL"
 }
 
  output_bottom()
-{ echo          >> "${FINAL}"
-  echo --       >> "${FINAL}"
-  echo "${FOOTERTXT}" >> "${FINAL}"
-  if [ -e "${BOT_TPL}" ]; then
-    cat "${BOT_TPL}" >> "${FINAL}"
+{ echo          >> "$FINAL"
+  echo --       >> "$FINAL"
+  echo "$FOOTERTXT" >> "$FINAL"
+  if [ -e "$BOT_TPL" ]; then
+    cat "$BOT_TPL" >> "$FINAL"
   else
-    echo "</pre>" >>  "${FINAL}"
-    echo "</body>" >>  "${FINAL}"
-    echo "</html>" >>  "${FINAL}"
+    echo "</pre>" >>  "$FINAL"
+    echo "</body>" >>  "$FINAL"
+    echo "</html>" >>  "$FINAL"
   fi
 } 
 
@@ -255,19 +255,19 @@ CUSTOM_SETUP=default_setup
 
  format_with_groff()
 { #sed 1liner from http://sed.sourceforge.net/sed1line.txt
-  groff -man -Tascii "${RAW}" >> bla.raw
-  sed '/^$/N;/\n$/D' bla.raw >> "${FINAL}"
+  groff -man -Tascii "$RAW" >> bla.raw
+  sed '/^$/N;/\n$/D' bla.raw >> "$FINAL"
   rm bla.raw
-#  groff -man -Tascii "${RAW}" >> "${FINAL}"
+#  groff -man -Tascii "$RAW" >> "$FINAL"
 }
 
  with_no_formatting()
-{ cat "${RAW}" >> "${FINAL}"
+{ cat "$RAW" >> "$FINAL"
 } 
 
  format_with_fold()
-{ if [ 0 -lt ${MARGIN} ]; then
-    fold -s -w ${MARGIN} "${RAW}" >> "${FINAL}"
+{ if [ 0 -lt $MARGIN ]; then
+    fold -s -w $MARGIN "$RAW" >> "$FINAL"
   else
     with_no_formatting 
   fi
@@ -278,136 +278,136 @@ CUSTOM_SETUP=default_setup
 # default arguments include:
 #
  preformat()
-{ if [ -e "${PREFORMAT_HOOK}" ]; then
-    if [ -x "${PREFORMAT_HOOK}" ]; then
-      cat "${DRAFT}" | "${PREFORMAT_HOOK}" "${FORMAT_FUNC}" > "${DRAFT}.tmp" 
-      mv -f "${DRAFT}.tmp" "${DRAFT}" 
+{ if [ -e "$PREFORMAT_HOOK" ]; then
+    if [ -x "$PREFORMAT_HOOK" ]; then
+      cat "$DRAFT" | "$PREFORMAT_HOOK" "$FORMAT_FUNC" > "$DRAFT.tmp" 
+      mv -f "$DRAFT.tmp" "$DRAFT" 
     fi
   fi 
 }
 
 # postformat()
-#{ if [ -x "${POSTFORMAT_HOOK}" ]; then
-#    cat "${FINAL}" | "${POSTFORMAT_HOOK}" > "${FINAL}.tmp" 
-#    mv -f "${FINAL}.tmp" "${FINAL}" 
+#{ if [ -x "$POSTFORMAT_HOOK" ]; then
+#    cat "$FINAL" | "$POSTFORMAT_HOOK" > "$FINAL.tmp" 
+#    mv -f "$FINAL.tmp" "$FINAL" 
 #  fi 
 #}
 
  format_main()
-{ FINAL=${DIR}/${1}
-  FINALNAME=${1}
-  RAW=${DIR}/${2}
-  RAWNAME=${2}
+{ FINAL=$DIR/$1}
+  FINALNAME=$1
+  RAW=$DIR/$2
+  RAWNAME=$2
   preformat
   # save raw form before formatting if it doesn't exist
   # which is the case when reformatting all
-  if [ ! -e "${RAW}" ]; then
-    echo "${DATE}"   > "${RAW}"     # in RAW, line 1 is date
-    echo          >> "${RAW}"
-    echo "${TITLE}" >> "${RAW}"     # in RAW, line 2 is title
-    echo          >> "${RAW}"
-    echo "--"     >> "${RAW}"
-    echo          >> "${RAW}"     # this blank line is important
-    cat "${DRAFT}"  >> "${RAW}"
+  if [ ! -e "$RAW" ]; then
+    echo "$DATE"   > "$RAW"     # in RAW, line 1 is date
+    echo          >> "$RAW"
+    echo "$TITLE" >> "$RAW"     # in RAW, line 2 is title
+    echo          >> "$RAW"
+    echo "--"     >> "$RAW"
+    echo          >> "$RAW"     # this blank line is important
+    cat "$DRAFT"  >> "$RAW"
   fi
-  ${OUTPUT_TOP} 
-  ${FORMAT_FUNC} 
-  ${OUTPUT_BOT} 
+  $OUTPUT_TOP 
+  $FORMAT_FUNC 
+  $OUTPUT_BOT 
   #postformat # not sure about this one yet
 }
 
  reformat_singleton()
-{  if [ -e "${DIR}/${1}.raw" ]; then
-     #echo "Reformatting message: \"${1}\""
-     cat "${DIR}/${1}.raw" > "${DRAFT}"
-     format_main "${1}.${FORMAT}" "${1}.raw"
+{  if [ -e "$DIR/$1.raw" ]; then
+     #echo "Reformatting message: \"$1\""
+     cat "$DIR/$1.raw" > "$DRAFT"
+     format_main "$1.$FORMAT" "$1.raw"
    fi
 }
 
  reformat_all()
-{ FILES=$(ls -c "${DIR}"/*.raw | "${SORT_OLDEST}")
+{ FILES=$(ls -c "$DIR"/*.raw | "$SORT_OLDEST")
    for RAW in "$FILES"; do
      # From: Randall R Schulz <rrschulz at cris dot com>
-     FULLNAME="${RAW}"
+     FULLNAME="$RAW"
      DIR=${FULLNAME%/*}
      FILE=${FULLNAME##*/}
      MAXBASE=${FILE%.*}
      MINBASE=${FILE%%.*}
      MAXSUF=${FILE#*.}
      MINSUF=${FILE##*.}
-     reformat_singleton "${MAXBASE}"
+     reformat_singleton "$MAXBASE"
    done
 }
 
  newest_first() 
-{ FILES=$(ls -c "${DIR}"/*.raw | "${SORT_NEWEST}")
-  echo "${FILES}"
+{ FILES=$(ls -c "$DIR"/*.raw | "$SORT_NEWEST")
+  echo "$FILES"
 }
 
  list_newest_first()
 { FILES=$(newest_first)
   COUNT=1
-  for FILE in "${FILES}"; do
-     FULLNAME=${FILE}
+  for FILE in "$FILES"; do
+     FULLNAME=$FILE
      DIR=${FULLNAME%/*}
      FILE=${FULLNAME##*/}
      MAXBASE=${FILE%.*}
-	 TITLE=$(head -n 3 "${DIR}/${FILE}" | tail -n 1) 
+	 TITLE=$(head -n 3 "$DIR/$FILE" | tail -n 1) 
      printf "%7d)  " "$COUNT"
-     echo "${MAXBASE} ::  ${TITLE}"
+     echo "$MAXBASE ::  $TITLE"
 	 COUNT=$(expr $COUNT + 1)
   done
 }
 
  oldest_first()
-{ FILES=$(ls -c "${DIR}"/*.raw | "${SORT_OLDEST}")
-  echo "${FILES}"
+{ FILES=$(ls -c "$DIR"/*.raw | "$SORT_OLDEST")
+  echo "$FILES"
 }
 
  list_oldest_first()
 { FILES=$(oldest_first)
-  for FILE in "${FILES}"; do
-     FULLNAME=${FILE}
+  for FILE in "$FILES"; do
+     FULLNAME=$FILE
      DIR=${FULLNAME%/*}
      FILE=${FULLNAME##*/}
      MAXBASE=${FILE%.*}
-	 TITLE=$(head -n 3 "${DIR}/${FILE}" | tail -n 1) 
-     echo "${MAXBASE} ::  ${TITLE}"
+	 TITLE=$(head -n 3 "$DIR/$FILE" | tail -n 1) 
+     echo "$MAXBASE ::  $TITLE"
   done
 }
 
  get_path2post()
-{ FILES=$(ls -c "${DIR}"/*.raw | "${SORT_NEWEST}")
-  GOAL=${1}
+{ FILES=$(ls -c "$DIR"/*.raw | "$SORT_NEWEST")
+  GOAL=$1
   COUNT=1
-  for FILE in "${FILES}"; do
-     FULLNAME=${FILE}
+  for FILE in "$FILES"; do
+     FULLNAME=$FILE
      DIR=${FULLNAME%/*}
      FILE=${FULLNAME##*/}
      MAXBASE=${FILE%.*}
-    if [ "${COUNT}" -eq "${GOAL}" ]; then
-     echo "${MAXBASE}"
+    if [ "$COUNT" -eq "$GOAL" ]; then
+     echo "$MAXBASE"
      break
     fi
-	COUNT=$(expr "${COUNT}" + 1)
+	COUNT=$(expr "$COUNT" + 1)
   done
 }
 
  purge_entries()
 { LEVEL=$1 
   COUNT=0
-  if [ ! -e "${INDEX}" ]; then
-    echo "Can't find index, \"${INDEX}\""
+  if [ ! -e "$INDEX" ]; then
+    echo "Can't find index, \"$INDEX\""
     die_cleanly
   fi
   FILES=$(newest_first)
-  for FILE in "${FILES}"; do
-     FULLNAME=${FILE}
+  for FILE in "$FILES"; do
+     FULLNAME=$FILE
      DIR=${FULLNAME%/*}
      FILE=${FULLNAME##*/}
      MAXBASE=${FILE%.*}
 	 ENTRY=$(grep "$MAXBASE" "$INDEX")
-     if [ -z "${ENTRY}" ]; then
+     if [ -z "$ENTRY" ]; then
 	   COUNT=$(expr "$COUNT" + 1)
        if [ "$LEVEL" -eq 1 ]; then
          echo "$DIR/$FILE (not really purged, use -P for realz)"
@@ -421,8 +421,8 @@ CUSTOM_SETUP=default_setup
 }
 
  die_cleanly()
-{ if [ -e "${DRAFT}" ]; then
-    rm -f "${DRAFT}"
+{ if [ -e "$DRAFT" ]; then
+    rm -f "$DRAFT"
   fi
   exit 0
 }
@@ -438,35 +438,35 @@ SET_DEFAULT_FORMAT_FUNC=
 # get opts ! stdin append to anything passed in by -m 
 while getopts 'f:m:t:T:c:d:i:IbB:hRr:lL:novx:X:Pps:' option; do
     case $option in
-    i) INDEX=${OPTARG}  # specify INDEX to $OPTARG
+    i) INDEX=$OPTARG  # specify INDEX to $OPTARG
        ;;
     I) INDEX="index.html" # force INDEX to index.html
        ;;
-    d) if [ -d "${OPTARG}" ]; then
-         cd "${OPTARG}"
+    d) if [ -d "$OPTARG" ]; then
+         cd "$OPTARG"
        else
-         echo "${OPTARG}" is not a directory!
+         echo "$OPTARG" is not a directory!
          die_cleanly
        fi
        ;;
-    r) POST2REFORMAT=${OPTARG}
+    r) POST2REFORMAT=$OPTARG
        ;;
     R) REFORMATALL=1
        ;;
     b) LISTENSTDIN=1 
        USE_EDITOR=0
        ;;
-    B) BOT_TPL=${OPTARG}
+    B) BOT_TPL=$OPTARG
        ;;
-    f) SET_DEFAULT_FORMAT_FUNC=${OPTARG}
+    f) SET_DEFAULT_FORMAT_FUNC=$OPTARG
        ;;
-    c) MARGIN=${OPTARG} # this option is about to be deprecated
+    c) MARGIN=$OPTARG # this option is about to be deprecated
        ;;
     l) POST2EDIT=1
        ;;
-    L) POST2EDIT=${OPTARG}
+    L) POST2EDIT=$OPTARG
        ;;
-    m) MESSAGE=${OPTARG} 
+    m) MESSAGE=$OPTARG 
        USE_EDITOR=0
        ;;
     n) list_newest_first
@@ -475,11 +475,11 @@ while getopts 'f:m:t:T:c:d:i:IbB:hRr:lL:novx:X:Pps:' option; do
     o) list_oldest_first
        die_cleanly 
        ;; 
-    s) SUMMARY=${OPTARG}
+    s) SUMMARY=$OPTARG
        ;; 
-    t) TITLE=${OPTARG}
+    t) TITLE=$OPTARG
        ;;
-    T) TOP_TPL=${OPTARG}
+    T) TOP_TPL=$OPTARG
        ;;
     v) echo $VERSION
        die_cleanly
@@ -491,7 +491,7 @@ while getopts 'f:m:t:T:c:d:i:IbB:hRr:lL:novx:X:Pps:' option; do
     h) usage
        die_cleanly
        ;;
-    x) PREFORMAT_HOOK=${OPTARG}
+    x) PREFORMAT_HOOK=$OPTARG
        ;; 
     ?) #usage | less
        die_cleanly
@@ -500,54 +500,54 @@ while getopts 'f:m:t:T:c:d:i:IbB:hRr:lL:novx:X:Pps:' option; do
 done
 
  post_opts() 
-{ if [ -e "${FORMAT_CUSTOM_DEFS}" ]; then
-    . "${FORMAT_CUSTOM_DEFS}"
+{ if [ -e "$FORMAT_CUSTOM_DEFS" ]; then
+    . "$FORMAT_CUSTOM_DEFS"
   fi
 
-  if [ -n "${SET_DEFAULT_FORMAT_FUNC}" ]; then 
-    "${FORMAT_DISPATCHER}" "${OPTARG}"  # default is set_format_func
+  if [ -n "$SET_DEFAULT_FORMAT_FUNC" ]; then 
+    "$FORMAT_DISPATCHER" "$OPTARG"  # default is set_format_func
   fi
 
-  if [ "${PURGELEVEL}" -ge 1 ]; then
-    purge_entries "${PURGELEVEL}"
+  if [ "$PURGELEVEL" -ge 1 ]; then
+    purge_entries "$PURGELEVEL"
     die_cleanly
   fi 
 
-  if [ "${POST2EDIT}" -ge 1 ]; then
-	LATEST=$(get_path2post "${POST2EDIT}")
-    ${EDITOR} "${DIR}/${LATEST}.raw"
-    POST2REFORMAT=${POST2EDIT}
+  if [ "$POST2EDIT" -ge 1 ]; then
+	LATEST=$(get_path2post "$POST2EDIT")
+    $EDITOR "$DIR/$LATEST.raw"
+    POST2REFORMAT=$POST2EDIT
   fi
 
-  if [ "${POST2REFORMAT}" -ge 1 ]; then
-	LATEST=$(get_path2post "${POST2REFORMAT}")
-    reformat_singleton "${LATEST}"
+  if [ "$POST2REFORMAT" -ge 1 ]; then
+	LATEST=$(get_path2post "$POST2REFORMAT")
+    reformat_singleton "$LATEST"
     die_cleanly
   fi
 
   # if "-R", or reformat all, is set 
-  if [ "${REFORMATALL}" -eq 1 ]; then
+  if [ "$REFORMATALL" -eq 1 ]; then
     # future may yield seperate "rebuild reindex" functionality 
     reformat_all
     die_cleanly
   fi
 
   # blocks vee -l (without the -r) from going on 
-  if [ "${POST2EDIT}" -ge 1 ]; then
+  if [ "$POST2EDIT" -ge 1 ]; then
     die_cleanly
   fi
 
   # Batch message creation: -m and stdin
   # handles -m
-  if [ -n "${MESSAGE}" ]; then
-    echo "${MESSAGE}" >> "${DRAFT}"
+  if [ -n "$MESSAGE" ]; then
+    echo "$MESSAGE" >> "$DRAFT"
   fi
 
-  if [ ${LISTENSTDIN} -eq 1 ]; then
+  if [ $LISTENSTDIN -eq 1 ]; then
     IFS="" # ensures that leading spaces are retained
     while read -r IN <&0 ; do # break after 1 sec of no stdin
-      echo "${IN}"            # echo's stdin back out so user can see 
-      echo "${IN}" >> "${DRAFT}" 
+      echo "$IN"            # echo's stdin back out so user can see 
+      echo "$IN" >> "$DRAFT" 
       LISTENSTDIN=1
       USE_EDITOR=0
     done
@@ -556,20 +556,20 @@ done
 
 # generates INDEX file if none exists
  default_setup()
-{ mkdir -p "${DIR}" || echo "${DIR}" exists...
-  if [ ! -e "${INDEX}" ]; then
+{ mkdir -p "$DIR" || echo "$DIR" exists...
+  if [ ! -e "$INDEX" ]; then
     echo
-    echo "...creating ${INDEX}"
-    echo "<!-- ;10000000000000000000000000; open pre tag --><!-- <?xml version=\"1.0\" encoding=\"UTF-8\" ?> --><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head><title>my vee index</title><meta http-equiv=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\"></head><body><pre>" >> "${INDEX}"
+    echo "...creating $INDEX"
+    echo "<!-- ;10000000000000000000000000; open pre tag --><!-- <?xml version=\"1.0\" encoding=\"UTF-8\" ?> --><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\"><head><title>my vee index</title><meta http-equiv=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\"></head><body><pre>" >> "$INDEX"
    # header stuff
-    echo "<!-- ;100000000000000000000000; fixed content -->" >> "${INDEX}"
-    echo "<!-- ;10000000000000000000000;  fixed content -->" >> "${INDEX}"
-    echo "<!-- ;1000000000000000000000;   fixed content -->" >> "${INDEX}"
+    echo "<!-- ;100000000000000000000000; fixed content -->" >> "$INDEX"
+    echo "<!-- ;10000000000000000000000;  fixed content -->" >> "$INDEX"
+    echo "<!-- ;1000000000000000000000;   fixed content -->" >> "$INDEX"
    # footer stuff
-    echo "<!-- ;3; fixed content -->" >> "${INDEX}"
-    echo "<!-- ;2; fixed content -->" >> "${INDEX}"
-    echo "<!-- ;1; fixed content -->Powered by <a href=\"http://www.0x743.com/vee\">vee</a>" >> "${INDEX}"
-    echo "<!-- ;0; closing pre tag --></pre></body></html>" >> "${INDEX}"
+    echo "<!-- ;3; fixed content -->" >> "$INDEX"
+    echo "<!-- ;2; fixed content -->" >> "$INDEX"
+    echo "<!-- ;1; fixed content -->Powered by <a href=\"http://www.0x743.com/vee\">vee</a>" >> "$INDEX"
+    echo "<!-- ;0; closing pre tag --></pre></body></html>" >> "$INDEX"
     echo
   fi
 }
@@ -577,14 +577,14 @@ done
  sort_index()
 {
   # would like to figure out how to put this sort command into a variable, but thusfar not so successful
-  sort -t';' +0f -1 +1nr "${INDEX}" > ".${INDEX}.$$.sorted"
-  mv ".${INDEX}.$$.sorted" "${INDEX}" # "rebuild ${INDEX}
+  sort -t';' +0f -1 +1nr "$INDEX" > ".$INDEX.$$.sorted"
+  mv ".$INDEX.$$.sorted" "$INDEX" # "rebuild $INDEX
 }
 
  use_editor()
-{ if [ ${USE_EDITOR} -eq 1 ]; then 
+{ if [ $USE_EDITOR -eq 1 ]; then 
     OK=0
-    ${EDITOR} "${DRAFT}" && OK=1
+    $EDITOR "$DRAFT" && OK=1
     if [ "$OK" -ne 1 ]; then
       echo there has been a problem with your editor session
       exit
@@ -597,7 +597,7 @@ done
 # ask for title if not set with -t and not in batch mode
 # if in batch mode with no -t set, use default title below
  get_title()
-{ if [ -z "${TITLE}"  ]; then
+{ if [ -z "$TITLE"  ]; then
     TITLE=$DEFAULT_TITLE
   fi
 }
@@ -618,14 +618,14 @@ post_opts
 get_title 
 use_editor
 
-if [ -e "${DRAFT}" ]; then
-  RAWFILE="$$.${SEC}.${TIME}.raw" # uses process id, $$, assuming there will
+if [ -e "$DRAFT" ]; then
+  RAWFILE="$$.$SEC.$TIME.raw" # uses process id, $$, assuming there will
                                   # not be duplicate process ids within 1 sec of each other
-  format_main "${SEC}.${TIME}.${FORMAT}" "$RAWFILE" 
+  format_main "$SEC.$TIME.$FORMAT" "$RAWFILE" 
   "$UPDATE_INDEX" 
   sort_index
   die_cleanly
 else
-  echo Error! "${DRAFT}" not found
+  echo Error! "$DRAFT" not found
 fi
 
