added support for groff-utf8 if it is found; did not test the case for when it is found - only fallback mode

diff --git a/trunk/bin/vee b/trunk/bin/vee
--- a/trunk/bin/vee
+++ b/trunk/bin/vee
@@ -89,6 +89,9 @@ function set_format_func
     groff)   FORMAT_FUNC=format_with_groff
              echo using $FORMAT_FUNC
              ;;
+    groff-utf8) FORMAT_FUNC=format_with_groff_utf8
+             echo using $FORMAT_FUNC
+             ;;
     fold)    FORMAT_FUNC=format_with_fold
              echo using $FORMAT_FUNC
              ;;
@@ -180,6 +183,7 @@ function output_top
      echo "<pre>"   >> ${FINAL}
    else
      echo "<!-- <?xml version=\"1.0\" encoding=\"UTF-8\" ?> --><!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\"><html xmlns=\"http://www.w3.org/1999/xhtml\">"  >> ${FINAL}
+     echo "<meta http-equiv=\"Content-Type\" CONTENT=\"text/html; charset=UTF-8\">" >> ${FINAL}
      echo "<head><title>${TITLE} - ${DATE}</title></head>"  >> ${FINAL}
      echo "<body>"  >> ${FINAL}
      echo "<pre>"   >> ${FINAL}
@@ -204,22 +208,32 @@ function output_bottom
 # begin formatting funcs
 
 function format_with_groff
-{
-  #sed 1liner from http://sed.sourceforge.net/sed1line.txt
+{ #sed 1liner from http://sed.sourceforge.net/sed1line.txt
   groff -man -Tascii ${RAW} >> bla.raw
   sed '/^$/N;/\n$/D' bla.raw >> ${FINAL}
   rm bla.raw
 #  groff -man -Tascii ${RAW} >> ${FINAL}
 }
 
+function format_with_groff_utf8
+{ #sed 1liner from http://sed.sourceforge.net/sed1line.txt
+  exe=`which groff-utf8 2> /dev/null || echo -1`
+  if [ "-1" != ${exe} ]; then
+    groff-utf8 -man -Tutf8 ${RAW} >> bla.raw
+    sed '/^$/N;/\n$/D' bla.raw >> ${FINAL}
+    rm bla.raw
+  else
+    echo "Warning: groff-utf8 not found, falling back to format_with_groff"
+    format_with_groff
+  fi
+}
+
 function with_no_formatting
-{
-  cat ${RAW} >> ${FINAL}
+{ cat ${RAW} >> ${FINAL}
 } 
 
 function format_with_fold
-{
-  if [ 0 -lt "${MARGIN}" ]; then
+{ if [ 0 -lt "${MARGIN}" ]; then
     fold -s -w ${MARGIN} ${RAW} >> ${FINAL}
   else
     with_no_formatting 
